swagger: "2.0"
info:
  description: "MangaRock API documentation\nBase URL: https://api.mangarockhd.com/query/web401\n\nAll OIDs are formated `mrs-<type>-<number>`"
  version: "1.0.0"
  title: "MangaRock API"
host: "cors-anywhere.herokuapp.com"
basePath: "/https://api.mangarockhd.com/query/web401"
tags:
- name: "updated"
  description: "recently updated mangas"
- name: "list"
  description: "list all mangas/authors/etc."
- name: "info"
  description: "get info on an object"
- name: "search"
  description: "search for a specific object"
- name: "read"
  description: "read a chapter (Pages are in an unknown 'MRI' file format that needs decryption)"
- name: "recommendation"
  description: "best to read next"
- name: "unknown"
  description: "not self explaining queries"
schemes:
- "https"
paths:
  /foryou:
    get:
      tags:
      - "unknown"
      summary: "TODO"
      description: ""
      parameters:
      - $ref: "#/parameters/msid"
      responses:
        200:
          description: ""
  /realtime:
    get:
      tags:
      - "unknown"
      summary: "TODO"
      description: ""
      parameters:
      - $ref: "#/parameters/msid"
      responses:
        200:
          description: ""
  /mrs_home_latest:
    get:
      tags:
      - "updated"
      summary: "Latest updates"
      description: ""
      responses:
        200:
          description: ""
          schema:
            type: "object"
            properties:
              code:
                $ref: "#/definitions/return-code"
              data:
                type: "array"
                items:
                  type: "object"
                  properties:
                    oid:
                      type: "string"
                    name:
                      type: "string"
                    genres:
                      type: "array"
                      items:
                        type: "string"
                    rank:
                      type: "integer"
                    updated_chapter:
                      type: "integer"
                    new_chapters:
                      type: "array"
                      items:
                        type: "object"
                        properties:
                          oid:
                            type: "string"
                          name:
                            type: "string"
                          updatedAt:
                            type: "string"
                            format: "date-time"
                    completed:
                      type: "boolean"
                      default: false
                    thumbnail:
                      type: "string"
                      description: "PNG or JPEG"
                    updated_at:
                      type: "string"
                      format: "date-time"
  /mrs_home_hot_updates:
    $ref: "#/paths/~1mrs_home_latest"
  /mrs_latest:
    $ref: "#/paths/~1mrs_home_latest"
  /mrs_filter:
    post:
      tags:
      - "list"
      summary: "All mangas available on the web site"
      description: ""
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          type: "object"
          properties:
            genres:
              type: "object"
              additionalProperties:
                type: "integer"
                default: 0
            order:
              type: "string"
              default: "rank"
              enum:
              - "rank"
              - "name"
            rank:
              type: "string"
              default: "all"
              enum:
              - "all"
              - "1-999"
              - "1000-2000"
              - "2000-3000"
            status:
              type: "string"
              default: "all"
              enum:
              - "all"
              - "completed"
              - "ongoing"
          example:
            genres: {}
            order: "all"
            rank: "all"
            status: "all"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/list"
  /license:
    post:
      tags:
      - "unknown"
      summary: "TODO"
      description: ""
      parameters:
      - $ref: "#/parameters/msid"
      responses:
        200:
          description: ""
  /mrs_quick_search:
    post:
      tags:
      - "search"
      summary: "search while typing"
      description: ""
      consumes:
      - "text/plain"
      parameters:
      - in: "body"
        name: "query"
        required: true
        schema:
          type: "string"
          example: "one"
      responses:
        200:
          description: ""
          schema:
            type: "object"
            properties:
              code:
                $ref: "#/definitions/return-code"
              data:
                type: "object"
                properties:
                  author:
                    type: "array"
                    items:
                      type: "string"
                  character:
                    type: "array"
                    items:
                      type: "string"
                  serie:
                    type: "array"
                    items:
                      type: "string"
  /mrs_search:
    post:
      tags:
      - "search"
      summary: "full search"
      description: ""
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          type: "object"
          properties:
            keywords:
              type: "string"
            type:
              type: "string"
              enum:
              - "series"
              - "author"
              - "character"
          example:
            keywords: "one"
            type: "series"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/list"
  /manga_detail:
    post:
      tags:
      - "info"
      summary: "query info on one or more manga"
      description: ""
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          type: "object"
          properties:
            oids:
              type: "object"
              properties:
                additionalProperties:
                  type: "integer"
                  default: 0
            sections:
              type: "array"
              items:
                $ref: "#/definitions/section"
          example:
            oids:
              mrs-serie-100159890: 0
            sections:
            - "basic_info"
            - "summary"
            - "artworks"
            - "sub_genres"
            - "social_stats"
            - "author"
            - "character"
            - "publisher"
            - "scanlator"
            - "other_fact"
            - "chapters"
            - "related_series"
            - "same_author"
            - "feature_collections"
      responses:
        200:
          description: ""
          schema:
            type: "object"
            properties:
              code:
                $ref: "#/definitions/return-code"
              data:
                type: "object"
                properties:
                  additionalProperties:
                    type: "object"
                    properties:
                      feature_collections:
                        type: "object"
                        properties:
                          collections:
                            type: "array"
                            items:
                              type: "string"
                      artworks:
                        type: "object"
                        properties:
                          artworks:
                            type: "array"
                            items:
                              type: "string"
                      author:
                        type: "object"
                        properties:
                          authors:
                            type: "array"
                            items:
                              type: "object"
                              properties:
                                oid:
                                  type: "string"
                                role:
                                  type: "string"
                      default:
                        type: "object"
                        properties:
                          oid:
                            type: "string"
                          mid:
                            type: "integer"
                          msid:
                            type: "integer"
                          last_updated:
                            type: "integer"
                      social_stats:
                        type: "object"
                        properties:
                          rank:
                            type: "integer"
                          read:
                            type: "integer"
                      basic_info:
                        type: "object"
                        properties:
                          name:
                            type: "string"
                          thumbnail:
                            type: "string"
                          thumbnail_extra:
                            type: "object"
                            properties:
                              generated:
                                type: "boolean"
                              averageColor:
                                type: "string"
                              textBackgroundColor:
                                type: "string"
                              textColor:
                                type: "string"
                          cover:
                            type: "string"
                          cover_extra:
                              type: "object"
                              properties:
                                generated:
                                  type: "boolean"
                                averageColor:
                                  type: "string"
                                textBackgroundColor:
                                  type: "string"
                                textColor:
                                  type: "string"
                          alias:
                            type: "array"
                            items:
                              type: "string"
                          rank:
                            type: "integer"
                          removed:
                            type: "boolean"
                          author:
                            type: "string"
                          completed:
                            type: "boolean"
                          direction:
                            type: "integer"
                          categories:
                            type: "array"
                            items:
                              type: "integer"
                          total_chapters:
                            type: "integer"
                          description:
                            type: "string"
                          release_frequency:
                            type: "object"
                            properties:
                              type:
                                type: "string"
                              unit:
                                type: "string"
                              amount:
                                type: "integer"
                          mrs_series:
                            type: "string"
                      summary:
                        type: "object"
                        properties:
                          plot_points:
                            type: "array"
                            items:
                              type: "string"
                          key_genres:
                            type: "array"
                            items:
                              type: "string"
                      other_fact:
                        type: "object"
                        properties:
                          extra:
                            type: "object"
                            properties:
                              additionalProperties:
                                type: "string"
                      same_author:
                        type: "object"
                        properties:
                          series:
                            type: "array"
                            items:
                              type: "string"
                      chapters:
                        type: "object"
                        properties:
                          chapters:
                            type: "array"
                            items:
                              type: "object"
                              properties:
                                cid:
                                  type: "integer"
                                oid:
                                  type: "integer"
                                name:
                                  type: "string"
                                last_updated:
                                  type: "integer"
                                order:
                                  type: "integer"
                      sub_genres:
                        type: "object"
                        properties:
                          sub_genres:
                            type: "array"
                            items:
                              type: "string"
                            
          
  /rec_similar_series_ml:
    get:
      tags:
      - "recommendation"
      summary: "TODO"
      description: ""
      parameters:
      - $ref: "#/parameters/msid"
      - $ref: "#/parameters/serie-oid"
      responses:
        200:
          description: ""
  /rec_because_you_read_ml:
    $ref: "#/paths/~1rec_similar_series_ml"
  /rec_recommendation_ml:
    get:
      tags:
      - "recommendation"
      summary: "TODO"
      description: ""
      parameters:
      - $ref: "#/parameters/msid"
      responses:
        200:
          description: ""
  /rec_btrn:
    post:
      tags:
      - "recommendation"
      summary: "TODO (best to read next)"
      description: ""
      parameters:
      - $ref: "#/parameters/msid"
      - $ref: "#/parameters/serie-oid"
      responses:
        200:
          description: ""
  /pagesv2:
    get:
      tags:
      - "read"
      summary: "TODO"
      description: ""
      parameters:
      - $ref: "#/parameters/chapter-oid"
      responses:
        200:
          description: ""
  /mrs_all_character:
    post:
      tags:
      - "list"
      summary: "TODO"
      description: ""
      parameters:
      - $ref: "#/parameters/name"
      responses:
        200:
          description: ""
  /character:
    get:
      tags:
      - "info"
      summary: "TODO"
      description: ""
      parameters:
      - $ref: "#/parameters/character-oid"
      responses:
        200:
          description: ""
  /mrs_serie_related_character:
    post:
      tags:
      - "info"
      summary: "TODO"
      description: ""
      parameters:
      - $ref: "#/parameters/character-oid"
      responses:
        200:
          description: ""
  /mrs_all_author:
    post:
      tags:
      - "list"
      summary: "TODO"
      description: ""
      parameters:
      - $ref: "#/parameters/name"
      responses:
        200:
          description: ""
  /author:
    post:
      tags:
      - "info"
      summary: "TODO"
      description: ""
      parameters:
      - $ref: "#/parameters/author-oid"
      responses:
        200:
          description: ""
  /genre:
    post:
      tags:
      - "info"
      summary: "TODO"
      description: ""
      parameters:
      - $ref: "#/parameters/genre-oid"
      responses:
        200:
          description: ""
  /mrs_serie_related_author:
    post:
      tags:
      - "info"
      summary: "TODO"
      description: ""
      parameters:
      - $ref: "#/parameters/author-oid"
      responses:
        200:
          description: ""
  /collection:
    post:
      tags:
      - "info"
      summary: "TODO"
      description: ""
      parameters:
      - $ref: "#/parameters/collection-oid"
      responses:
        200:
          description: ""
parameters:
  msid:
    in: "query"
    name: "msid"
    description: ""
    required: true
    type: "integer"
    default: 71
  serie-oid:
    in: "query"
    name: "oid"
    description: ""
    required: true
    type: "string"
    pattern: "mrs-serie-\\d+"
    default: "mrs-serie-100159890"
  chapter-oid:
    in: "query"
    name: "oid"
    description: ""
    required: true
    type: "string"
    pattern: "mrs-chapter-\\d+"
    default: "mrs-chapter-200179435"
  genre-oid:
    in: "query"
    name: "oid"
    description: ""
    required: true
    type: "string"
    pattern: "mrs-genre-\\d+"
    default: "mrs-genre-304068"
  character-oid:
    in: "query"
    name: "oid"
    description: ""
    required: true
    type: "string"
    pattern: "mrs-character-\\d+"
    default: "mrs-character-304068"
  collection-oid:
    in: "query"
    name: "oid"
    description: ""
    required: true
    type: "string"
    pattern: "mrs-collection-\\d+"
    default: "mrs-collection-100384825"
  author-oid:
    in: "query"
    name: "oid"
    description: ""
    required: true
    type: "string"
    pattern: "mrs-author-\\d+"
    default: "mrs-author-100171605"
  name:
    in: "body"
    name: "body"
    description: "restrict list"
    required: true
    schema:
      type: "object"
      properties:
        name:
          type: "string"
          pattern: "[A-Z]?"
          default: ""
definitions:
  return-code:
    type: "integer"
    default: 0
  list:
    type: "object"
    properties:
      code:
        $ref: "#/definitions/return-code"
      data:
        type: "array"
        items:
          type: "string"
  section:
    type: "string"
    enum:
    - "basic_info"
    - "summary"
    - "artworks"
    - "sub_genres"
    - "social_stats"
    - "author"
    - "character"
    - "publisher"
    - "scanlator"
    - "other_fact"
    - "chapters"
    - "related_series"
    - "same_author"
    - "feature_collections"
